### PR TITLE
Create more clarity on current ATO timelines

### PR DESCRIPTION
**Pull request by NoahKunin**
Making sure expectations are being level set!

### CODE REVIEW

**Comment by annahsgraves** [comment]
fyi @rdpiazza

**Comment by NoahKunin** [comment]
Getting this out is extremely urgent, so I'll be merging COB today, given there were no comments by @jroo. 

Please flag if any issues @rdpiazza.

**Comment by rdpiazza** [comment]
@NoahKunin I'm good with this!  I'm OK for you to merge, or happy to do so.

**Comment by NoahKunin** [comment]
Merging!

**Pull request merged**
