### PR TITLE
Update to guides_style_18f v0.3.0, add search config

### LINKED ISSUE #31: Lifecycle of a Project nav item won't expand
Try clicking the `+` next to "Lifecycle of a Project" in the sidebar...doesn't seem to be working, so none of the pages beneath it are accessible. Not seeing any JavaScript errors, so not immediately obvious why that would be the case. Maybe a page metadata / `navigation` in `_config.yml` issue?

/cc @mbland

### PR DESCRIPTION
**Pull request by mbland**
Closes #31. I think. Think that problem is related to 18F/guides-style#20. Note that the fix won't appear at https://pages.18f.gov/product-guide/ until this branch is merged into `18f-pages` (or the commit here is cherry-picked into it).

Also enables `jekyll_pages_api_search`.

cc: @afeld

### CODE REVIEW

**Comment by afeld** [comment]
:clap: Thanks for the :zap: turnaround!

**Comment by afeld** [comment]
Hmm, seems to have caused a new issue:

screen shot 2016-01-28 at 11 10 29 pm

**Comment by mbland** [comment]
I know what that is... Need to update https://pages-staging.18f.gov/guides-template/ so it grabs the updated CSS. (Thought I did that already...)

**Comment by mbland** [comment]
OK, I confused pages badly by doing nasty tricks with the `18f-pages-staging` and `18f-pages-internal` branches that I thought were clever. https://pages-staging.18f.gov/guides-template/ is back in a good state, and consequently, so is https://pages-staging.18f.gov/product-guide/, as it pulls it CSS from the guides-template.

**Pull request merged**
